/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as BaiVietIndexRouteImport } from './routes/bai-viet.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as BaiVietSlugRouteImport } from './routes/bai-viet.$slug'
import { Route as AdminSanPhamRouteImport } from './routes/admin.san-pham'
import { Route as AdminDonHangRouteImport } from './routes/admin.don-hang'
import { Route as AdminBaiVietRouteImport } from './routes/admin.bai-viet'

const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietIndexRoute = BaiVietIndexRouteImport.update({
  id: '/bai-viet/',
  path: '/bai-viet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietSlugRoute = BaiVietSlugRouteImport.update({
  id: '/bai-viet/$slug',
  path: '/bai-viet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSanPhamRoute = AdminSanPhamRouteImport.update({
  id: '/san-pham',
  path: '/san-pham',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonHangRoute = AdminDonHangRouteImport.update({
  id: '/don-hang',
  path: '/don-hang',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBaiVietRoute = AdminBaiVietRouteImport.update({
  id: '/bai-viet',
  path: '/bai-viet',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dang-nhap': typeof DangNhapRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/admin/bai-viet': typeof AdminBaiVietRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/san-pham': typeof AdminSanPhamRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bai-viet/': typeof BaiVietIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/admin/bai-viet': typeof AdminBaiVietRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/san-pham': typeof AdminSanPhamRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bai-viet': typeof BaiVietIndexRoute
  '/san-pham': typeof SanPhamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dang-nhap': typeof DangNhapRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/admin/bai-viet': typeof AdminBaiVietRoute
  '/admin/don-hang': typeof AdminDonHangRoute
  '/admin/san-pham': typeof AdminSanPhamRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bai-viet/': typeof BaiVietIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dang-nhap'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/admin/bai-viet'
    | '/admin/don-hang'
    | '/admin/san-pham'
    | '/bai-viet/$slug'
    | '/san-pham/$slug'
    | '/admin/'
    | '/bai-viet/'
    | '/san-pham/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dang-nhap'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/admin/bai-viet'
    | '/admin/don-hang'
    | '/admin/san-pham'
    | '/bai-viet/$slug'
    | '/san-pham/$slug'
    | '/admin'
    | '/bai-viet'
    | '/san-pham'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dang-nhap'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/admin/bai-viet'
    | '/admin/don-hang'
    | '/admin/san-pham'
    | '/bai-viet/$slug'
    | '/san-pham/$slug'
    | '/admin/'
    | '/bai-viet/'
    | '/san-pham/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DangNhapRoute: typeof DangNhapRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  ThanhToanRoute: typeof ThanhToanRoute
  BaiVietSlugRoute: typeof BaiVietSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  BaiVietIndexRoute: typeof BaiVietIndexRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/': {
      id: '/bai-viet/'
      path: '/bai-viet'
      fullPath: '/bai-viet/'
      preLoaderRoute: typeof BaiVietIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/$slug': {
      id: '/bai-viet/$slug'
      path: '/bai-viet/$slug'
      fullPath: '/bai-viet/$slug'
      preLoaderRoute: typeof BaiVietSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/san-pham': {
      id: '/admin/san-pham'
      path: '/san-pham'
      fullPath: '/admin/san-pham'
      preLoaderRoute: typeof AdminSanPhamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/don-hang': {
      id: '/admin/don-hang'
      path: '/don-hang'
      fullPath: '/admin/don-hang'
      preLoaderRoute: typeof AdminDonHangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bai-viet': {
      id: '/admin/bai-viet'
      path: '/bai-viet'
      fullPath: '/admin/bai-viet'
      preLoaderRoute: typeof AdminBaiVietRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBaiVietRoute: typeof AdminBaiVietRoute
  AdminDonHangRoute: typeof AdminDonHangRoute
  AdminSanPhamRoute: typeof AdminSanPhamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBaiVietRoute: AdminBaiVietRoute,
  AdminDonHangRoute: AdminDonHangRoute,
  AdminSanPhamRoute: AdminSanPhamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DangNhapRoute: DangNhapRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  ThanhToanRoute: ThanhToanRoute,
  BaiVietSlugRoute: BaiVietSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  BaiVietIndexRoute: BaiVietIndexRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
